export interface PropertyData {
  id: string
  slug: string
  name: string
  tagline: string
  description: string
  propertyType: string
  bhk: string | null
  bhkNumber: number | null
  price: number
  priceLabel: string
  pricePerSqft: number | null
  areaSqft: number | null
  carpetArea: number | null
  builtUpArea: number | null
  location: string
  city: string
  address: string | null
  possessionStatus: string | null
  furnishing: string | null
  transactionType: string | null
  builder: string | null
  floorCount: number | null
  featured: boolean
  premium: boolean
  reraRegistered: boolean
  reraId: string | null
  images: string[]
  floorPlans: string[]
  amenities: string[]
  nearbyLandmarks: string[]
  brochureUrl: string | null
  videoTourUrl: string | null
  mapEmbedUrl: string | null
  views: number
  likes: number
  inquiries: number
  status: string
}

export interface TestimonialData {
  id: string
  clientName: string
  clientImage: string | null
  clientLocation: string | null
  propertyPurchased: string | null
  rating: number
  testimonial: string
  investmentStory: string | null
  videoUrl: string | null
  featured: boolean
}

export interface LeadData {
  id: string
  name: string
  email: string | null
  phone: string
  propertyId: string | null
  leadType: string
  message: string | null
  source: string | null
  status: string
  contactHistory: string[]
  createdAt: string
}

export interface NotificationData {
  id: string
  type: string
  title: string
  message: string
  leadId: string | null
  propertyId: string | null
  isRead: boolean
  createdAt: string
}

// Mumbai luxury property images
const PROPERTY_IMAGES = {
  chembur: [
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
  ],
  kurla: [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop',
  ],
  ghatkopar: [
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
  ],
  thane: [
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop',
  ],
  naviMumbai: [
    'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop',
  ],
}

export const PROPERTIES: PropertyData[] = [
  {
    id: '1',
    slug: 'arihant-sky-chembur',
    name: 'Arihant Sky',
    tagline: 'Welcome to a Life Blessed with Abundance',
    description: 'Indulge in a lifestyle where modern conveniences meet serene surroundings, offering the perfect blend of comfort and elegance. Arihant Sky stands tall as a beacon of luxury living in Chembur East, Mumbai. Strategically located just 5 minutes from Chembur Station, this premium residential tower offers breathtaking views of the city skyline along with world-class amenities that redefine urban living. Every residence is thoughtfully designed to maximize natural light and ventilation, creating homes that are both beautiful and functional. The project features meticulously planned 1 and 2 BHK apartments with premium finishes, modular kitchens, and elegant bathrooms that reflect the highest standards of quality craftsmanship.',
    propertyType: 'Apartment',
    bhk: '1, 2 BHK',
    bhkNumber: 2,
    price: 16900000,
    priceLabel: '₹1.23 Cr - ₹1.69 Cr',
    pricePerSqft: 22533,
    areaSqft: 750,
    carpetArea: 618,
    builtUpArea: 750,
    location: 'Chembur East',
    city: 'Mumbai',
    address: 'Chembur East, Mumbai - 400071',
    possessionStatus: 'Under Construction',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Arihant Group',
    floorCount: 28,
    featured: true,
    premium: true,
    reraRegistered: true,
    reraId: 'P52000012345',
    images: PROPERTY_IMAGES.chembur,
    floorPlans: [],
    amenities: ['Swimming Pool', 'Gymnasium', 'Children Play Area', 'Jogging Track', 'Club House', 'Power Backup', '24/7 Security', 'Intercom', 'Landscaped Gardens', 'Indoor Games', 'Multipurpose Hall', 'Rainwater Harvesting'],
    nearbyLandmarks: ['Chembur Station - 5 min', 'Eastern Express Highway - 3 min', 'Diamond Garden - 10 min', 'Chembur Monorail - 7 min', 'Fine Restaurants & Malls - 5 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 245,
    likes: 38,
    inquiries: 12,
    status: 'active',
  },
  {
    id: '2',
    slug: 'hubtown-rising-city-ghatkopar',
    name: 'Hubtown Rising City',
    tagline: 'An Indulgence Beyond Any Experience Known So Far',
    description: 'A city breaker within the city! Hubtown Rising City is a luxury project spread over 100 acres of land with 17 towers of 28 storeys each, providing you with premium 1, 2, and 3 BHK homes. This landmark development by Hubtown Limited is designed to offer an unparalleled living experience with meticulously planned residences that feature premium finishes, spacious layouts, and panoramic views of the Mumbai skyline. The township concept ensures that every necessity and luxury is within walking distance, from world-class amenities to retail spaces and recreational facilities. Rising City is not just a home; it is a complete lifestyle destination that caters to every aspect of modern urban living.',
    propertyType: 'Apartment',
    bhk: '1, 2, 3 BHK',
    bhkNumber: 3,
    price: 30800000,
    priceLabel: '₹1.85 Cr - ₹3.08 Cr',
    pricePerSqft: 28087,
    areaSqft: 1096,
    carpetArea: 900,
    builtUpArea: 1096,
    location: 'Ghatkopar East',
    city: 'Mumbai',
    address: 'Mumbai Harbour, Ghatkopar East, Mumbai - 400077',
    possessionStatus: 'Under Construction',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Hubtown Limited',
    floorCount: 28,
    featured: true,
    premium: true,
    reraRegistered: true,
    reraId: 'P52000067890',
    images: PROPERTY_IMAGES.ghatkopar,
    floorPlans: [],
    amenities: ['Swimming Pool', 'Gymnasium', 'Tennis Court', 'Badminton Court', 'Jogging Track', 'Club House', 'Power Backup', '24/7 Security', 'CCTV Surveillance', 'Intercom', 'Landscaped Gardens', 'Indoor Games', 'Mini Theatre', 'Co-working Space', 'Retail Plaza', 'Creche'],
    nearbyLandmarks: ['Ghatkopar Station - 10 min', 'Eastern Express Highway - 5 min', 'R-City Mall - 8 min', 'Fortis Hospital - 12 min', 'International Airport - 20 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 312,
    likes: 54,
    inquiries: 18,
    status: 'active',
  },
  {
    id: '3',
    slug: 'sky-heights-kurla',
    name: 'Sky Heights',
    tagline: 'Elevate Your Living Experience',
    description: 'Sky Heights presents a collection of exquisitely designed 2 BHK apartments in the heart of Kurla, Mumbai. These premium residences combine contemporary architecture with thoughtful design, creating spaces that are both elegant and functional. Each apartment features spacious rooms with abundant natural light, premium flooring, modular kitchens with granite countertops, and elegantly designed bathrooms with premium fixtures. The project offers a range of lifestyle amenities including a rooftop swimming pool, state-of-the-art gymnasium, and landscaped gardens. Located in Kurla, one of Mumbai\'s most well-connected suburbs, Sky Heights ensures seamless connectivity to BKC, South Mumbai, and the upcoming metro corridor.',
    propertyType: 'Apartment',
    bhk: '2 BHK',
    bhkNumber: 2,
    price: 13500000,
    priceLabel: '₹1.35 Cr',
    pricePerSqft: 18000,
    areaSqft: 750,
    carpetArea: 618,
    builtUpArea: 750,
    location: 'Kurla',
    city: 'Mumbai',
    address: 'Kurla, Mumbai - 400070',
    possessionStatus: 'Ready to Move',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Sky Builders',
    floorCount: 22,
    featured: true,
    premium: false,
    reraRegistered: true,
    reraId: 'P52000023456',
    images: PROPERTY_IMAGES.kurla,
    floorPlans: [],
    amenities: ['Gymnasium', 'Children Play Area', 'Power Backup', '24/7 Security', 'Intercom', 'Landscaped Gardens', 'Indoor Games', 'Multipurpose Hall', 'Parking'],
    nearbyLandmarks: ['Kurla Station - 5 min', 'BKC - 15 min', 'Phoenix Marketcity - 8 min', 'Kohinoor Hospital - 10 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 178,
    likes: 24,
    inquiries: 8,
    status: 'active',
  },
  {
    id: '4',
    slug: 'nehru-nagar-1bhk-kurla',
    name: 'Nehru Nagar Residences',
    tagline: 'Smart Living in the Heart of Mumbai',
    description: 'Nehru Nagar Residences offers a perfect blend of comfort and convenience with its thoughtfully designed 1 BHK apartments in Kurla East. These fully furnished apartments are ideal for young professionals and investors looking for a ready-to-move-in property in a prime location. The apartments come equipped with modern fittings, modular kitchens, and wardrobes, making them completely move-in ready. The building features modern amenities and excellent connectivity to Mumbai\'s business districts, making daily commute effortless. With property values in Kurla East showing consistent appreciation, this is also an excellent investment opportunity with strong rental potential.',
    propertyType: 'Apartment',
    bhk: '1 BHK',
    bhkNumber: 1,
    price: 10500000,
    priceLabel: '₹1.05 Cr',
    pricePerSqft: 19811,
    areaSqft: 530,
    carpetArea: 464,
    builtUpArea: 530,
    location: 'Nehru Nagar, Kurla East',
    city: 'Mumbai',
    address: 'Nehru Nagar, Kurla East, Mumbai - 400070',
    possessionStatus: 'Ready to Move',
    furnishing: 'Furnished',
    transactionType: 'New Property',
    builder: 'Nehru Builders',
    floorCount: 18,
    featured: false,
    premium: false,
    reraRegistered: true,
    reraId: 'P52000034567',
    images: PROPERTY_IMAGES.kurla,
    floorPlans: [],
    amenities: ['Gymnasium', 'Power Backup', '24/7 Security', 'Intercom', 'Parking', 'CCTV Surveillance'],
    nearbyLandmarks: ['Kurla Station - 3 min', 'BKC - 12 min', 'R-City Mall - 5 min', 'LBS Marg - 2 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 134,
    likes: 16,
    inquiries: 5,
    status: 'active',
  },
  {
    id: '5',
    slug: 'skyline-villa-chembur',
    name: 'Skyline Villa CHS',
    tagline: 'Where Comfort Meets Convenience',
    description: 'Skyline Villa CHS Ltd presents premium 2 BHK apartments in the bustling neighborhood of Nehru Nagar, Kurla East. This resale property offers excellent value in a well-established cooperative housing society with all modern amenities and a strong community feel. The apartment features spacious rooms with good ventilation, a well-designed kitchen, and a balcony with city views. The society is well-maintained with landscaped gardens, children\'s play area, and dedicated parking. Located in a prime area of Kurla East, it offers easy access to schools, hospitals, shopping centers, and public transport. This is an excellent opportunity for homebuyers looking for a ready-to-move-in property in a well-connected locality at an attractive price point.',
    propertyType: 'Apartment',
    bhk: '2 BHK',
    bhkNumber: 2,
    price: 11700000,
    priceLabel: '₹1.17 Cr',
    pricePerSqft: 21667,
    areaSqft: 540,
    carpetArea: 540,
    builtUpArea: 580,
    location: 'Nehru Nagar, Kurla East',
    city: 'Mumbai',
    address: 'Skyline Villa CHS, Nehru Nagar, Kurla East, Mumbai',
    possessionStatus: 'Ready to Move',
    furnishing: 'Unfurnished',
    transactionType: 'Resale Property',
    builder: 'Skyline Developers',
    floorCount: 14,
    featured: false,
    premium: false,
    reraRegistered: false,
    reraId: null,
    images: PROPERTY_IMAGES.chembur,
    floorPlans: [],
    amenities: ['Children Play Area', 'Power Backup', 'Security', 'Parking', 'Garden'],
    nearbyLandmarks: ['Kurla Station - 5 min', 'BKC - 15 min', 'Schools & Hospitals - 5 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 98,
    likes: 11,
    inquiries: 4,
    status: 'active',
  },
  {
    id: '6',
    slug: 'royal-villa-atgaon',
    name: 'Royal Villa',
    tagline: 'Your Private Villa Retreat',
    description: 'Royal Villa offers an exclusive opportunity to own a private villa in the peaceful surroundings of Atgaon, Thane. Spread across a generous built-up area, these 1 BHK villas provide the perfect escape from the hustle and bustle of city life while maintaining excellent connectivity to Mumbai via the local train network. Each villa comes with a private garden, terrace area, and dedicated parking space. The community features landscaped gardens, walking paths, and a clubhouse with recreational facilities. Atgaon\'s serene environment, combined with the rapidly developing infrastructure of the Shahapur region, makes this an ideal investment for those seeking a second home or a peaceful retirement retreat. The area is witnessing significant development with upcoming infrastructure projects that promise excellent appreciation potential.',
    propertyType: 'Villa',
    bhk: '1 BHK',
    bhkNumber: 1,
    price: 4500000,
    priceLabel: '₹45 L',
    pricePerSqft: 3982,
    areaSqft: 1130,
    carpetArea: 1000,
    builtUpArea: 1130,
    location: 'Atgaon',
    city: 'Thane',
    address: 'Atgaon, Shahapur, Thane - 421301',
    possessionStatus: 'Ready to Move',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Royal Builders',
    floorCount: 2,
    featured: false,
    premium: false,
    reraRegistered: false,
    reraId: null,
    images: PROPERTY_IMAGES.thane,
    floorPlans: [],
    amenities: ['Private Garden', 'Terrace', 'Parking', 'Club House', 'Walking Path', '24/7 Security'],
    nearbyLandmarks: ['Atgaon Station - 5 min', 'Shahapur Town - 10 min', 'Highway - 15 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 156,
    likes: 22,
    inquiries: 7,
    status: 'active',
  },
  {
    id: '7',
    slug: 'chembur-luxury-2bhk',
    name: 'Chembur Luxury Towers',
    tagline: 'Luxury Redefined in Chembur',
    description: 'Chembur Luxury Towers presents an exclusive collection of 2 BHK apartments in one of Mumbai\'s most sought-after residential neighborhoods. These premium apartments feature spacious layouts with elegant interiors, premium flooring, and designer bathrooms. The project boasts a range of world-class amenities including a rooftop infinity pool, sky lounge, and a fully equipped fitness center. Located in Chembur, residents enjoy excellent connectivity to BKC, South Mumbai, and Navi Mumbai through the Eastern Freeway, Monorail, and upcoming metro lines. The neighborhood offers a perfect blend of urban convenience and suburban tranquility with renowned schools, hospitals, shopping malls, and fine dining restaurants all within easy reach.',
    propertyType: 'Apartment',
    bhk: '2 BHK',
    bhkNumber: 2,
    price: 12700000,
    priceLabel: '₹1.27 Cr',
    pricePerSqft: 21167,
    areaSqft: 600,
    carpetArea: 600,
    builtUpArea: 650,
    location: 'Chembur',
    city: 'Mumbai',
    address: 'Chembur, Mumbai - 400071',
    possessionStatus: 'New Property',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Chembur Developers',
    floorCount: 25,
    featured: true,
    premium: true,
    reraRegistered: true,
    reraId: 'P52000045678',
    images: PROPERTY_IMAGES.chembur,
    floorPlans: [],
    amenities: ['Rooftop Infinity Pool', 'Sky Lounge', 'Gymnasium', 'Spa', 'Children Play Area', 'Jogging Track', 'Club House', 'Power Backup', '24/7 Security', 'CCTV', 'Concierge', 'EV Charging'],
    nearbyLandmarks: ['Chembur Station - 5 min', 'Eastern Freeway - 3 min', 'BKC - 15 min', 'Cubbon Park - 10 min', 'Fine Dining Hub - 5 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 289,
    likes: 42,
    inquiries: 15,
    status: 'active',
  },
  {
    id: '8',
    slug: 'vision-aanand-plot-atgaon',
    name: 'Vision Aanand',
    tagline: 'Build Your Dream Home',
    description: 'Vision Aanand offers premium residential plots in the rapidly developing area of Atgaon, Thane. These NA bungalow plots provide an excellent opportunity to build your dream home in a serene, green environment with excellent connectivity to Mumbai. Each plot is clearly demarcated with proper fencing and access roads, and the project has all necessary approvals and NA permissions in place. The surrounding area is witnessing rapid development with new infrastructure projects, educational institutions, and commercial establishments coming up in the vicinity. Whether you are looking to build your dream home or make a smart investment in land, Vision Aanand plots offer tremendous value with strong appreciation potential driven by the region\'s growth trajectory.',
    propertyType: 'Plot',
    bhk: null,
    bhkNumber: null,
    price: 1200000,
    priceLabel: '₹12 L',
    pricePerSqft: 575,
    areaSqft: 2088,
    carpetArea: null,
    builtUpArea: null,
    location: 'Atgaon',
    city: 'Thane',
    address: 'Atgaon, Shahapur, Thane - 421301',
    possessionStatus: 'Ready to Move',
    furnishing: null,
    transactionType: 'New Property',
    builder: 'Vision Developers',
    floorCount: null,
    featured: false,
    premium: false,
    reraRegistered: false,
    reraId: null,
    images: PROPERTY_IMAGES.thane,
    floorPlans: [],
    amenities: ['Gated Community', 'Internal Roads', 'Water Supply', 'Electricity', 'Landscaped Garden', 'Security'],
    nearbyLandmarks: ['Atgaon Station - 5 min', 'Highway - 10 min', 'Shahapur Market - 8 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 112,
    likes: 18,
    inquiries: 9,
    status: 'active',
  },
  {
    id: '9',
    slug: 'panvel-premium-2bhk',
    name: 'Panvel Platinum Heights',
    tagline: 'Gateway to Premium Living',
    description: 'Panvel Platinum Heights offers luxurious 2 BHK apartments in the rapidly growing node of Panvel, Navi Mumbai. As the upcoming infrastructure hub of the Mumbai Metropolitan Region, Panvel is witnessing unprecedented growth with the Navi Mumbai International Airport, Mumbai Trans-Harbour Link, and multiple metro lines under construction. These premium apartments feature modern designs with spacious layouts, premium finishes, and abundant natural light. The project offers a comprehensive range of amenities designed for contemporary urban living. With property prices in Panvel still competitive compared to other Navi Mumbai nodes, this is an excellent investment opportunity with strong appreciation potential driven by the upcoming infrastructure developments.',
    propertyType: 'Apartment',
    bhk: '2 BHK',
    bhkNumber: 2,
    price: 9500000,
    priceLabel: '₹95 L',
    pricePerSqft: 15200,
    areaSqft: 625,
    carpetArea: 520,
    builtUpArea: 625,
    location: 'Panvel',
    city: 'Navi Mumbai',
    address: 'Panvel, Navi Mumbai - 410206',
    possessionStatus: 'Under Construction',
    furnishing: 'Unfurnished',
    transactionType: 'New Property',
    builder: 'Platinum Builders',
    floorCount: 20,
    featured: false,
    premium: false,
    reraRegistered: true,
    reraId: 'P52000056789',
    images: PROPERTY_IMAGES.naviMumbai,
    floorPlans: [],
    amenities: ['Swimming Pool', 'Gymnasium', 'Club House', 'Children Play Area', 'Jogging Track', 'Power Backup', '24/7 Security', 'Intercom', 'Garden', 'Parking'],
    nearbyLandmarks: ['Panvel Station - 5 min', 'Upcoming Airport - 15 min', 'Mumbai-Pune Expressway - 5 min', 'Karnala Bird Sanctuary - 10 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 198,
    likes: 29,
    inquiries: 11,
    status: 'active',
  },
  {
    id: '10',
    slug: 'matunga-luxury-3bhk',
    name: 'Matunga Heritage Towers',
    tagline: 'Heritage Elegance, Modern Luxury',
    description: 'Matunga Heritage Towers brings together the timeless charm of Matunga\'s heritage with contemporary luxury living. These exclusive 3 BHK apartments are designed for discerning homeowners who appreciate fine craftsmanship and elegant living spaces. Each apartment features premium Italian marble flooring, designer modular kitchens, and luxurious bathrooms with imported fixtures. The project offers a boutique living experience with limited residences per floor ensuring privacy and exclusivity. Located in Matunga, one of Mumbai\'s most culturally rich and well-connected neighborhoods, residents enjoy proximity to renowned educational institutions, traditional South Indian restaurants, vibrant markets, and excellent rail connectivity to both Western and Central lines.',
    propertyType: 'Apartment',
    bhk: '3 BHK',
    bhkNumber: 3,
    price: 28000000,
    priceLabel: '₹2.80 Cr',
    pricePerSqft: 35000,
    areaSqft: 800,
    carpetArea: 680,
    builtUpArea: 800,
    location: 'Matunga',
    city: 'Mumbai',
    address: 'Matunga, Mumbai - 400019',
    possessionStatus: 'Ready to Move',
    furnishing: 'Semi-Furnished',
    transactionType: 'New Property',
    builder: 'Heritage Developers',
    floorCount: 15,
    featured: true,
    premium: true,
    reraRegistered: true,
    reraId: 'P52000067891',
    images: PROPERTY_IMAGES.kurla,
    floorPlans: [],
    amenities: ['Italian Marble Flooring', 'Concierge Service', 'Rooftop Garden', 'Gymnasium', 'Spa', 'Children Play Area', 'Power Backup', '24/7 Security', 'EV Charging', 'Smart Home Features'],
    nearbyLandmarks: ['Matunga Station - 3 min', 'Dadar - 5 min', 'BKC - 20 min', 'Premium Schools - 5 min', 'Café Matunga - 2 min'],
    brochureUrl: null,
    videoTourUrl: null,
    mapEmbedUrl: null,
    views: 267,
    likes: 45,
    inquiries: 19,
    status: 'active',
  },
]

export const TESTIMONIALS: TestimonialData[] = [
  {
    id: '1',
    clientName: 'Nikhil Sharma',
    clientImage: null,
    clientLocation: 'Mumbai',
    propertyPurchased: 'Arihant Sky, Chembur East',
    rating: 5,
    testimonial: 'Working with New Era Reality was an exceptional experience from start to finish. Rohit and his team understood exactly what we were looking for and showed us properties that matched our requirements perfectly. Their knowledge of the Chembur market is unparalleled, and they guided us through every step of the purchase process with professionalism and care. The transparency and honesty they bring to the table is truly refreshing in the real estate industry.',
    investmentStory: 'We purchased a 2 BHK in Arihant Sky and have already seen significant appreciation in just 6 months. The team\'s advice on timing the market was spot on.',
    videoUrl: null,
    featured: true,
  },
  {
    id: '2',
    clientName: 'Sangram Panchal',
    clientImage: null,
    clientLocation: 'Kurla, Mumbai',
    propertyPurchased: 'Sky Heights, Kurla',
    rating: 4,
    testimonial: 'The agent from New Era Reality explained the registration process timeline clearly and made sure I understood every legal aspect of the property purchase. They were patient, knowledgeable, and always available to answer my questions. I felt well-informed throughout the entire process, which made a significant difference in my confidence as a first-time homebuyer.',
    investmentStory: null,
    videoUrl: null,
    featured: true,
  },
  {
    id: '3',
    clientName: 'Nilesh Patil',
    clientImage: null,
    clientLocation: 'Thane',
    propertyPurchased: 'Royal Villa, Atgaon',
    rating: 5,
    testimonial: 'New Era Reality knows Kurla East and the broader Mumbai builder reputation well. They helped me find the perfect villa in Atgaon that I wouldn\'t have discovered on my own. Their network and market intelligence is impressive, and they were able to negotiate a great deal on my behalf. The after-sales service has been excellent too - they continue to help with property management queries even after the sale is complete.',
    investmentStory: 'My villa in Atgaon has appreciated by 35% since I purchased it 8 months ago, thanks to the team\'s recommendation to invest in the Thane region.',
    videoUrl: null,
    featured: true,
  },
  {
    id: '4',
    clientName: 'Priya Mehta',
    clientImage: null,
    clientLocation: 'Navi Mumbai',
    propertyPurchased: 'Panvel Platinum Heights',
    rating: 5,
    testimonial: 'As a single woman investing in property for the first time, I was nervous about the entire process. New Era Reality made me feel completely at ease. They educated me about the market, helped me understand the financial aspects, and found me a beautiful 2 BHK in Panvel that fits my budget perfectly. Their commitment to client satisfaction is evident in every interaction, and I couldn\'t be happier with my investment decision.',
    investmentStory: 'With the new airport coming up, my property value has already increased by 20% and I expect it to double in the next 3-5 years.',
    videoUrl: null,
    featured: false,
  },
  {
    id: '5',
    clientName: 'Rajesh & Sunita Joshi',
    clientImage: null,
    clientLocation: 'Matunga, Mumbai',
    propertyPurchased: 'Matunga Heritage Towers',
    rating: 5,
    testimonial: 'We were looking for a premium 3 BHK in a heritage locality, and New Era Reality delivered beyond our expectations. Their understanding of luxury segment properties in Mumbai is remarkable. They arranged site visits at our convenience, provided detailed comparative analyses, and helped us negotiate favorable terms. The entire experience was seamless and professional, exactly what you expect from a top-tier real estate consultancy.',
    investmentStory: null,
    videoUrl: null,
    featured: true,
  },
  {
    id: '6',
    clientName: 'Darshan Kalathiya',
    clientImage: null,
    clientLocation: 'Ghatkopar, Mumbai',
    propertyPurchased: 'Hubtown Rising City',
    rating: 4,
    testimonial: 'Very professional service. The team at New Era Reality helped me navigate the complex process of buying a property in Hubtown Rising City. They were thorough in their documentation and made sure everything was in order before we proceeded. Their market insights about the Ghatkopar area helped me make an informed decision. I would definitely recommend them to anyone looking for reliable real estate services in Mumbai.',
    investmentStory: null,
    videoUrl: null,
    featured: false,
  },
]

export const SITE_STATS = {
  totalProperties: 150,
  happyClients: 500,
  yearsExperience: 10,
  citiesCovered: 3,
}

export const FEATURED_LOCATIONS = [
  { name: 'Chembur', city: 'Mumbai', count: 25, image: "Gemini_Generated_Image_j52byxj52byxj52b.png" },
  { name: 'Kurla East', city: 'Mumbai', count: 30, image: 'Gemini_Generated_Image_75i9pl75i9pl75i9.png' },
  { name: 'Ghatkopar', city: 'Mumbai', count: 20, image: "Gemini_Generated_Image_ao83b0ao83b0ao83.png" },
  { name: 'Matunga', city: 'Mumbai', count: 15, image: "a6a2082402c5d48b2715e3d69ed095b0.jpg" },
  { name: 'Panvel', city: 'Navi Mumbai', count: 35, image: "Gemini_Generated_Image_kdeddpkdeddpkded (1).png" },
  { name: 'Atgaon', city: 'Thane', count: 12, image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=600&h=400&fit=crop' },
]
